#ifndef __wxMarkDownEditormainFrame__
#define __wxMarkDownEditormainFrame__

/**
@file
Subclass of mainFrame, which is generated by wxFormBuilder.
*/

#include "gui/wxMarkDownEditorGUI.h"
#include "maddy/parser.h"
#include <wx/webview.h>
#include <wx/regex.h>

//// end generated include

/** Implementing mainFrame */
class wxMarkDownEditormainFrame : public mainFrame {
public:
    /** Constructor */
    wxMarkDownEditormainFrame(wxWindow* parent);
    void OnEditorChar(wxKeyEvent& event) override;
    void OnEditorKeyDown(wxKeyEvent& event) override;
    void OnEditorKeyUp(wxKeyEvent& event) override;
    void OnWebViewNavigating(wxWebViewEvent& event);
    //void OnHtmlLinkClicked(wxHtmlLinkEvent& event) override;
    /// menu item events
    void OnExit(wxCommandEvent& event) override;
    void OnSave(wxCommandEvent& event) override;
    void OnSaveAs(wxCommandEvent& event) override;
    void OnOpen(wxCommandEvent& event) override;
    /// opened files list
    void OnOpenFileActivated(wxDataViewEvent& event) override;

    /// splitter
    void OnSplitterSashPositionChanged(wxSplitterEvent& event) override;
    //// end generated class members

private:
    std::shared_ptr<maddy::ParserConfig> parserConfig = nullptr;
    std::shared_ptr<maddy::Parser> parser             = nullptr;
    bool editorContentChanged                         = false;
    std::map<wxString /*filename*/, wxString /*content*/> openFilesContent;
    std::map<wxString /*filename*/, wxString /*content*/> openFilesHtmlOutput;

    wxConfig* config = nullptr;
    wxFileName currentFileName;
    wxArrayString openFiles;
    wxString currentCssFile;
    wxWebView* webView = nullptr;

    void UpdatePreview(bool forceUpdate = false);

    const wxString FormatTimeAgo(const wxDateTime& lastModified);
    void LoadStylesFromConfig(const wxString& paletteName);
    void OnPaletteChange(wxCommandEvent& event);
    void CreateDefaultConfigFile(const wxString& configFilePath);
    void OpenFile(const wxString& fileName);
};

#endif  // __wxMarkDownEditormainFrame__
