name: Build C++ Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'true'
          path: wxmarkdowneditor

      - name: Cache wxWidgets
        uses: actions/cache@v3
        with:
          path: wxWidgets
          key: wxwidgets-3.2.6-${{ runner.os }}

      - name: Cache cmark-gfm
        uses: actions/cache@v3
        with:
          path: cmark-gfm
          key: cmark-gfm-${{ runner.os }}

      - name: Install dependencies (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y cmake g++ libgtk-3-dev libjpeg-dev libtiff-dev \
                              libpng-dev zlib1g-dev libexpat1-dev libgstreamer1.0-dev \
                              libgstreamer-plugins-base1.0-dev


      - name: Build wxWidgets from source
        run: |
          git clone --branch v3.2.6 --depth 1 https://github.com/wxWidgets/wxWidgets.git ${GITHUB_WORKSPACE}/wxWidgets
          cd ${GITHUB_WORKSPACE}/wxWidgets
          mkdir -p local_build
          cd local_build
          cmake .. -DCMAKE_INSTALL_PREFIX=${GITHUB_WORKSPACE}/wxWidgets-install -DCMAKE_BUILD_TYPE=Release -DwxBUILD_SHARED=OFF -DwxBUILD_TESTS=OFF
          cmake --build . --config Release --target install

      - name: Build and install cmark-gfm
        run: |
          git clone --recursive https://github.com/github/cmark-gfm.git cmark-gfm
          cd cmark-gfm
          mkdir -p build
          cd build
          cmake .. -DCMAKE_INSTALL_PREFIX=${GITHUB_WORKSPACE}/cmark-gfm-install -DCMAKE_BUILD_TYPE=Release -DCMARK_TESTS=OFF -DCMARK_STATIC=ON -DCMARK_SHARED=OFF
          cmake --build . --config Release --target install

      - name: Configure CMake
        run: |
          cd ${GITHUB_WORKSPACE}/wxmarkdowneditor
          cmake -B build -DWXWIDGETS_PATH=${GITHUB_WORKSPACE}/wxWidgets-install -DCMAKE_BUILD_TYPE=Release
        env:
          CMAKE_PREFIX_PATH: ${GITHUB_WORKSPACE}/cmark-gfm-install

      - name: Build project
        run: cmake --build build --config Release
